services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: elysia_server
        env_file:
            - apps/server/.env
        ports:
            - "3000:3000"
        restart: unless-stopped

    postgres:
        image: postgres:17-alpine
        container_name: postgres_container

        env_file:
            - apps/server/.env

        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"

        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        command: >
            postgres -c max_connections=1000
                     -c shared_buffers=256MB
                     -c effective_cache_size=768MB
                     -c maintenance_work_mem=64MB
                     -c checkpoint_completion_target=0.7
                     -c wal_buffers=16MB
                     -c default_statistics_target=100

volumes:
    pgdata:
        driver: local
